INSERT INTO `files` (`id`, `name`, `description`, `path`) VALUES 
('1', 'Vanilla_scoop', 'Vanilla', '/assets/frontend/images/vanilla.png'), 
('2', 'Strawberry_scoop', 'Strawberry', '/assets/frontend/images/strawberry.png'),
('3', 'Mango_scoop', 'Mango', '/assets/frontend/images/mango.png'),
('4', 'Chocolate_scoop', 'Chocolate', '/assets/frontend/images/chocolate.png'),
('5', 'Strawberry_Shaker shake', 'Strawberry_Shaker', '/assets/frontend/images/chocolate.png'),
('6', 'Blue Berry Shaker shake', 'Blue Berry Shaker', '/assets/frontend/images/2.png'),
('7', 'Late After Eight shake', 'Late After Eight', '/assets/frontend/images/3.png'),
('8', 'Chocolate Basbousa Shake', 'Chocolate Basbousa Shake', '/assets/frontend/images/4.png'),
('9', 'Kit Kat Fusion shake', 'Kit Kat Fusion', '/assets/frontend/images/5.png'),
('10', 'Choc-a-Lot shake', 'Choc-a-Lot', '/assets/frontend/images/6.png'),
('11', 'Basbousa Shake', 'Basbousa Shake', '/assets/frontend/images/7.png'),
('12', 'Caramilla shake', 'Caramilla Shake', '/assets/frontend/images/8.png'),
('13', 'The Hippy Shake', 'The Hippy Shake', '/assets/frontend/images/9.png'),
('14', 'Mango Dream Shake', 'Mango Dream Shake', '/assets/frontend/images/10.png'),
('15', 'Konafa Ice-Cream Sandwich plate', 'Konafa Ice-Cream Sandwich', '/assets/frontend/images/1-2.png'),
('16', 'Chocolate Time plate', 'Chocolate Time', '/assets/frontend/images/2-2.png'),
('17', 'Booster Scoopster plate', 'Booster Scoopster', '/assets/frontend/images/3-2.png'),
('18', 'Ice Raisin Crepe plate', 'Ice Raisin Crepe', '/assets/frontend/images/4-2.png'),
('19', 'Banana Split plate', 'Banana Split', '/assets/frontend/images/5-2.png'),
('20', 'Strawberry Dream plate', 'Strawberry Dream', '/assets/frontend/images/6-2.png'),
('21', 'Sugar High plate', 'Sugar High', '/assets/frontend/images/7-2.png'),
('22', 'Ice Gold Apples plate', 'Ice Gold Apples', '/assets/frontend/images/8-2.png'),
('23', 'Smooth Crunch plate', 'Smooth Crunch', '/assets/frontend/images/9-2.png'),
('24', 'Mango Konafa Madness plate', 'Mango Konafa Madness', '/assets/frontend/images/10-2.png'),
('25', 'Biscuit Crush plate', 'Biscuit Crush', '/assets/frontend/images/11-2.png'),
('26', 'Ice Donut plate', 'Ice Donut', '/assets/frontend/images/12-2.png'),
('27', 'Ice Chocolate Finger plate', 'Ice Chocolate Finger', '/assets/frontend/images/13-2.png'),
('28', 'Type A types', 'Type A', '/assets/frontend/images/typea.png'),
('29', 'Type B types', 'Type B', '/assets/frontend/images/typeb.png'),
('30', 'Type C types', 'Type C', '/assets/frontend/images/typec.png'),
('31', 'Type D types', 'Type D', '/assets/frontend/images/typed.png'),
('32', 'Type E types', 'Type E', '/assets/frontend/images/typee.png'),
('33', 'Type F types', 'Type F', '/assets/frontend/images/typef.png'),
('34', 'theme 1', 'Theme 1', '/assets/frontend/images/menu-1.png'),
('35', 'theme 2', 'Theme 2', '/assets/frontend/images/menu-2.png'),
('36', 'theme 3', 'Theme 3', '/assets/frontend/images/menu-3.png'),
('37', 'theme 4', 'Theme 4', '/assets/frontend/images/menu-4.png'),
('38', 'theme 5', 'Theme 5', '/assets/frontend/images/menu-5.png'),
('39', 'theme 6', 'Theme 6', '/assets/frontend/images/menu-6.png'),
('40', 'theme 7', 'Theme 7', '/assets/frontend/images/menu-7.png'),
('41', 'theme 8', 'Theme 8', '/assets/frontend/images/menu-8.png'),
('42', 'theme 9', 'Theme 9', '/assets/frontend/images/menu-9.png'),
('43', 'theme 10', 'Theme 10', '/assets/frontend/images/menu-10.png'),
('44', 'theme 11', 'Theme 11', '/assets/frontend/images/menu-11.png'),
('45', 'theme 12', 'Theme 12', '/assets/frontend/images/menu-12.png');


INSERT INTO `scope` (`id`, `name`, `img`) VALUES 
('1', 'Vanilla', '1'), 
('2', 'Strawberry', '2'),
('3', 'Mango', '3'),
('4', 'Chocolate', '4');

INSERT INTO `shake` (`id`, `name`, `img`) VALUES 
('1', 'The Strawberry Shaker', '5'),
('2', 'Blue Berry Shaker', '6'),
('3', 'Late After Eight', '7'),
('4', 'Chocolate Basbousa Shake', '8'),
('5', 'Kit Kat Fusion', '9'),
('6', 'Choc-a-Lot', '10'),
('7', 'Basbousa Shake', '11'),
('8', 'Caramilla Shake', '12'),
('9', 'The Hippy Shake', '13'),
('10', 'Mango Dream', '14');

INSERT INTO `plate` (`id`, `name`, `img`) VALUES 
('1', 'Konafa Ice-Cream Sandwich', '15'),
('2', 'Chocolate Time', '16'),
('3', 'Booster Scoopster', '17'),
('4', 'Ice Raisin Crepe', '18'),
('5', 'Banana Split', '19'),
('6', 'Strawberry Dream', '20'),
('7', 'Sugar High', '21'),
('8', 'Ice Gold Apples', '22'),
('9', 'Smooth Crunch', '23'),
('10', 'Mango Konafa Madness', '24'),
('11', 'Biscuit Crush', '25'),
('12', 'Ice Donut', '26'),
('13', 'Ice Chocolate Finger', '27');

INSERT INTO `shape` (`id`, `name`, `img`) VALUES 
('1', 'Type A', '28'),
('2', 'Type B', '29'),
('3', 'Type C', '30'),
('4', 'Type D', '31'),
('5', 'Type E', '32'),
('6', 'Type F', '33');

INSERT INTO `menu_theme` (`id`, `name`, `img`) VALUES 
('1', '1', '34'),
('2', '2', '34'),
('3', '3', '34'),
('4', '4', '34'),
('5', '5', '34'),
('6', '6', '34'),
('7', '7', '34'),
('8', '8', '34'),
('9', '9', '34'),
('10', '10', '34'),
('11', '11', '34'),
('12', '12', '34');